### ISSUE TITLE
Can't Differentiate isLoading from various request

### ISSUE THREAD

**Issue by robintiolie** [traveloka/react-load#2]
I want to differentiate isLoading is coming from specific method.
I think we can add the parameter 'type' to the @load('TYPE'). so the load props have new parameter called type.

**Comment by robintiolie** [comment]
current implementation is @load('KEY'). but the key itself never be used. it is always using LoadContext_1.K_DEFAULT_KEY which is 'tr4v3l0k4_4_4v3r'. why not passing the TYPE to the parameter and we can get the type from load result. so we have  
const {
      load: { isLoading,  type },
    } = this.props;

if(isLoading && type == 'SUBMIT') renderLoadingSubmit();
if(isLoading && type=='FETCH_FORM') renderLoadingForm();

USE CASE: I have one page that request multiple API. One from fetching the data. and submit. I want to differentiate loading between them.

**Comment by Jekiwijaya** [comment]
Whenever this is possible or not,

It's not recommended to a component have multiple role in fetching, usually the components is become to big, and you should broke the component to 2 containers, so each container have it's own role.

I on purpose make the default type is invisible, because commonly the needed of multiple value of loading is in the problem of the code design. But you still can do
```jsx
const { load: { getLoadingByKey } } = this.props;
const { isLoading, isError } = getLoadingByKey('FETCHING_USER_DETAIL')
```
But like I state above, I recommeded you to reflect the best approach in your usecase. Since the downside of using this API, that means your component would have multiple role, and would be hard to being maintain.
